Repository redferret/little-esty-shop, pull requests merged in 2021-06, with the labels that each got.

#69 Story 15
  app/controllers/admin/merchants_controller.rb
  app/views/admin/merchants/edit.html.erb
  app/views/admin/merchants/show.html.erb
  spec/features/admin/merchants/edit_spec.rb
  spec/features/admin/merchants/show_spec.rb
  spec/features/merchants/dashboard/index_spec.rb
Labels: enhancement

#72 Use active record to reset pk values
  Rakefile
Labels: invalid

#79 Api framework
  Gemfile
  Gemfile.lock
  app/apis/github_api/v3/api_exceptions.rb
  app/apis/github_api/v3/client.rb
  app/apis/github_api/v3/http_status_codes.rb
  spec/apis/github_api_v3/client_spec.rb
Labels: API Consumption

#77 Pretty html
  app/controllers/merchants/items_controller.rb
  app/helpers/admin_helper.rb
  app/helpers/item_helper.rb
  app/models/item.rb
  app/models/merchant.rb
  app/views/admin/invoices/show.html.erb
  app/views/admin/merchants/index.html.erb
  app/views/admin/merchants/new.html.erb
  app/views/admin/merchants/show.html.erb
  app/views/merchants/dashboard/index.html.erb
  app/views/merchants/invoices/index.html.erb
  app/views/merchants/invoices/show.html.erb
  app/views/merchants/items/edit.html.erb
  app/views/merchants/items/index.html.erb
  app/views/merchants/items/new.html.erb
  app/views/merchants/items/show.html.erb
  app/views/partials/admin/_enable_disable_merchants.html.erb
  app/views/partials/merchants/_enable_disable_item_table.html.erb
  app/views/partials/merchants/_navbar.html.erb
  db/migrate/20210605023825_create_column_status_for_item.rb
  spec/features/merchants/items/index_spec.rb
  spec/helpers/admin_helper_spec.rb
  spec/models/item_spec.rb
Labels: enhancement
